// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectList() {
  return window['go']['api']['App']['ConnectList']();
}

export function ConnectionCreate(arg1) {
  return window['go']['api']['App']['ConnectionCreate'](arg1);
}

export function ConnectionDelete(arg1) {
  return window['go']['api']['App']['ConnectionDelete'](arg1);
}

export function DBConnectList() {
  return window['go']['api']['App']['DBConnectList']();
}

export function DialDB(arg1) {
  return window['go']['api']['App']['DialDB'](arg1);
}
