// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {define} from '../models';

export function ConnectList():Promise<api.Response>;

export function ConnectionCreate(arg1:define.Connection):Promise<api.Response>;

export function ConnectionDelete(arg1:string):Promise<api.Response>;

export function DBConnectList():Promise<api.Response>;

export function DialDB(arg1:string):Promise<api.Response>;
